Фильтр по полям вложенных моделей
kr-aleksey/PyOData1C pull request #3
Opened 2024-12-10 17:56 UTC by AleksandrPU

Добавление возможности использовать фильтр по полям вложенных моделей.

Для того, чтобы проходила проверка на существование поля нужно в модель добавить описание вложенного поля.

Например, для фильтра по полю work_center_type_uid_1c вложенной модели work_centers нужно добавить в исходную модель:
```Python
work_centers__work_center_type_uid_1c: str = None
```
Тестирование надеюсь завершить на этой неделе.

2024-12-10 17:59 UTC, AleksandrPU commented
Неверно создал.

2024-12-12 14:30 UTC, AleksandrPU commented
Протестировал создание объектов Q: все методы работают.

2024-12-17 06:01 UTC, kr-aleksey requested changes
Код посмотрел, мне понравилось. Нехватает только описания в readme, как с этим работать.

2024-12-19 18:00 UTC, AleksandrPU reviewed
Добавил описание в readme и пример использования.

2024-12-23 08:17 UTC, kr-aleksey approved these changes

2024-12-23 08:17 UTC, merged